name: IMGWTools
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.26.4
  - pandas>=2.2.2
  - pyproj>=3.6.1
  - pyshp>=2.3.1
  - python=3.11.9
  - pywget>=3.2
  - requests>=2.32.3
  - scipy>=1.13.1
  - seaborn>=0.13.2
