column_names_dict = {
    "k_d": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Maksymalna temperatura dobowa",
        "Status pomiaru TMAX",
        "Minimalna temperatura dobowa",
        "Status pomiaru TMIN",
        "Średnia temperatura dobowa",
        "Status pomiaru STD",
        "Temperatura minimalna przy gruncie",
        "Status pomiaru TMNG",
        "Suma dobowa opadów",
        "Status pomiaru SMDB",
        "Rodzaj opadu",
        "Wysokość pokrywy śnieżnej",
        "Status pomiaru PKSN",
    ],
    "k_d_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Średnia dobowa temperatura",
        "Status pomiaru TEMP",
        "Średnia dobowa wilgotność względna",
        "Status pomiaru WLGS",
        "Średnia dobowa prędkość wiatru",
        "Status pomiaru FWS",
        "Średnie dobowe zachmurzenie ogólne",
        "Status pomiaru NOS",
    ],
    "k_m_d": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Absolutna temperatura maksymalna",
        "Status pomiaru TMAX",
        "Średnia temperatura maksymalna",
        "Status pomiaru TMXS",
        "Absolutna temperatura minimalna",
        "Status pomiaru TMIN",
        "Średnia temperatura minimalna",
        "Status pomiaru TMNS",
        "Średnia temperatura miesięczna",
        "Status pomiaru STM",
        "Minimalna temperatura przy gruncie",
        "Status pomiaru TMNG",
        "Miesieczna suma opadów",
        "Status pomiaru SUMM",
        "Maksymalna dobowa suma opadów",
        "Status pomiaru OPMX",
        "Pierwszy dzień wystąpienia opadu maksymalnego",
        "Ostatni dzień wystąpienia opadu maksymalnego",
        "Maksymalna wysokość pokrywy śnieżnej",
        "Status pomiaru PKSN",
        "Liczba dni z pokrywą śnieżną",
        "Liczba dni z opadem deszczu",
        "Liczba dni z opadem śniegu",
    ],
    "k_m_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Średnia miesięczna temperatura",
        "Status pomiaru TEMP",
        "Średnia miesięczna wilgotność względna",
        "Status pomiaru WLGS",
        "Średnia miesięczna prędkość wiatru",
        "Status pomiaru FWS",
        "Średnie miesięczne zachmurzenie ogólne",
        "Status pomiaru NOS",
    ],
    "k_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Godzina",
        "Temperatura powietrza",
        "Status pomiaru TEMP",
        "Temperatura termometru zwilżonego",
        "Status pomiaru TTZW",
        "Wskaźnik lodu",
        "Wskaźnik wentylacji",
        "Wilgotność względna",
        "Status pomiaru WLGW",
        "Kod kierunku wiatru",
        "Status pomiaru DKDK",
        "Prędkość wiatru",
        "Status pomiaru FWR",
        "Zachmurzenie ogólne",
        "Status pomiaru ZOGK",
        "Widzialność",
        "Status pomiaru WID",
    ],
    "o_d": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Suma dobowa opadów",
        "Status pomiaru SMDB",
        "Rodzaj opadu",
        "Wysokość pokrywy śnieżnej",
        "Status pomiaru PKSN",
        "Wysokość świeżospadłego śniegu",
        "Status pomiaru HSS",
        "Gatunek śniegu",
        "Status pomiaru GATS",
        "Rodzaj pokrywy śnieżnej",
        "Status pomiaru RPSN",
    ],
    "o_m": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Miesięczna suma opadów",
        "Status pomiaru SUMM",
        "Liczba dni z opadem śniegu",
        "Status pomiaru LDS",
        "Opad maksymalny",
        "Status pomiaru MAXO",
        "Dzień pierwszy wystąpienia opadu maksymalnego",
        "Dzień ostatni wystąpienia opadu maksymalnego",
        "Liczba dni z pokrywą śnieżną",
        "Status pomiaru LDPS",
    ],
    "s_d": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Maksymalna temperatura dobowa",
        "Status pomiaru TMAX",
        "Minimalna temperatura dobowa",
        "Status pomiaru TMIN",
        "Średnia temperatura dobowa",
        "Status pomiaru STD",
        "Temperatura minimalna przy gruncie",
        "Status pomiaru TMNG",
        "Suma dobowa opadu",
        "Status pomiaru SMDB",
        "Rodzaj opadu",
        "Wysokość pokrywy śnieżnej",
        "Status pomiaru PKSN",
        "Równoważnik wodny śniegu",
        "Status pomiaru RWSN",
        "Usłonecznienie",
        "Status pomiaru USL",
        "Czas trwania opadu deszczu",
        "Status pomiaru DESZ",
        "Czas trwania opadu śniegu",
        "Status pomiaru SNEG",
        "Czas trwania opadu deszczu ze śniegiem",
        "Status pomiaru DISN",
        "Czas trwania gradu",
        "Status pomiaru GRAD",
        "Czas trwania mgły",
        "Status pomiaru MGLA",
        "Czas trwania zamglenia",
        "Status pomiaru ZMGL",
        "Czas trwania sadzi",
        "Status pomiaru SADZ",
        "Czas trwania gołoledzi",
        "Status pomiaru GOLO",
        "Czas trwania zamieci śnieżnej niskiej",
        "Status pomiaru ZMNI",
        "Czas trwania zamieci śnieżnej wysokiej",
        "Status pomiaru ZMWS",
        "Czas trwania zmętnienia",
        "Status pomiaru ZMET",
        "Czas trwania wiatru >=10m/s",
        "Status pomiaru FF10",
        "Czas trwania wiatru >15m/s",
        "Status pomiaru FF15",
        "Czas trwania burzy",
        "Status pomiaru BRZA",
        "Czas trwania rosy",
        "Status pomiaru ROSA",
        "Czas trwania szronu",
        "Status pomiaru SZRO",
        "Wystąpienie pokrywy śnieżnej",
        "Status pomiaru DZPS",
        "Wystąpienie błyskawicy",
        "Status pomiaru DZBL",
        "Stan gruntu",
        "Izoterma dolna",
        "Status pomiaru IZD",
        "Izoterma górna",
        "Status pomiaru IZG",
        "Aktynometria",
        "Status pomiaru AKTN",
    ],
    "s_d_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Średnie dobowe zachmurzenie ogólne",
        "Status pomiaru NOS",
        "Średnia dobowa prędkość wiatru",
        "Status pomiaru FWS",
        "Średnia dobowa temperatura",
        "Status pomiaru TEMP",
        "Średnie dobowe ciśnienie pary wodnej",
        "Status pomiaru CPW",
        "Średnia dobowa wilgotność względna",
        "Status pomiaru WLGS",
        "Średnie dobowe ciśnienie na poziomie stacji",
        "Status pomiaru PPPS",
        "Średnie dobowe ciśnienie na poziomie morza",
        "Status pomiaru PPPM",
        "Suma opadu dzień",
        "Status pomiaru WODZ",
        "Suma opadu noc",
        "Status pomiaru WONO",
    ],
    "s_m_d": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Absolutna temperatura maksymalna",
        "Status pomiaru TMAX",
        "Średnia temperatura maksymalna",
        "Status pomiaru TMXS",
        "Absolutna temperatura minimalna",
        "Status pomiaru TMIN",
        "Średnia temperatura minimalna",
        "Status pomiaru TMNS",
        "Średnia temperatura miesięczna",
        "Status pomiaru STM",
        "Minimalna temperatura przy gruncie",
        "Status pomiaru TMNG",
        "Miesięczna suma opadów",
        "Status pomiaru SUMM",
        "Maksymalna dobowa suma opadów",
        "Status pomiaru OPMX",
        "Pierwszy dzień wystąpienia opadu maksymalnego",
        "Ostatni dzień wystąpienia opadu maksymalnego",
        "Miesięczna suma usłonecznienia",
        "Status pomiaru SUUS",
        "Maksymalna wysokość pokrywy śnieżnej",
        "Status pomiaru PKSN",
        "Liczba dni z pokrywą śnieżną",
        "Status pomiaru PSDN",
        "Liczba dni z opadem deszczu",
        "Status pomiaru DESD",
        "Liczba dni z opadem śniegu",
        "Status pomiaru SNID",
        "Liczba dni z opadem deszczu ze śniegiem",
        "Status pomiaru DSND",
        "Liczba dni z gradem",
        "Status pomiaru GRDD",
        "Liczba dni z mgłą",
        "Status pomiaru MGLD",
        "Liczba dni z zamgleniem",
        "Status pomiaru ZAMD",
        "Liczba dni z sadzią",
        "Status pomiaru SADD",
        "Liczba dni z gołoledzią",
        "Status pomiaru GOLD",
        "Liczba dni z zamiecią śnieżną niską",
        "Status pomiaru ZAND",
        "Liczba dni z zamiecią śnieżną wysoką",
        "Status pomiaru ZAWD",
        "Liczba dni ze zmętnieniem",
        "Status pomiaru ZMED",
        "Liczba dni z wiatrem >= 10m/s",
        "Status pomiaru W10D",
        "Liczba dni z wiatrem >15m/s",
        "Status pomiaru W15D",
        "Liczba dni z burzą",
        "Status pomiaru BURD",
        "Liczba dni z rosą",
        "Status pomiaru ROSD",
        "Liczba dni ze szronem",
        "Status pomiaru SZRD",
    ],
    "s_m_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Średnie miesięczne zachmurzenie ogólne",
        "Status pomiaru NOS",
        "Średnia miesięczna prędkość wiatru",
        "Status pomiaru FWS",
        "Średnia miesięczna temperatura",
        "Status pomiaru TEMP",
        "Średnie miesięczne ciśnienie pary wodnej",
        "Status pomiaru CPW",
        "Średnia miesięczna wilgotność względna",
        "Status pomiaru WLGS",
        "Średnie miesięczne ciśnienie na poziomie stacji",
        "Status pomiaru PPPS",
        "Średnie miesięczne ciśnienie na poziomie morza",
        "Status pomiaru PPPM",
        "Suma opadu dzień",
        "Status pomiaru WODZ",
        "Suma opadu noc",
        "Status pomiaru WONO",
    ],
    "s_t": [
        "Kod stacji",
        "Nazwa stacji",
        "Rok",
        "Miesiąc",
        "Dzień",
        "Godzina",
        "Wysokość podstawy chmur CL CM szyfrowana",
        "Status pomiaru HPOD",
        "Wysokość podstawy niższej",
        "Status pomiaru HPON",
        "Wysokość podstawy wyższej",
        "Status pomiaru HPOW",
        "Wysokość podstawy tekstowy",
        "Pomiar przyrządem 1 (niższa)",
        "Pomiar przyrządem 2 (wyższa)",
        "Widzialność",
        "Status pomiaru WID",
        "Widzialność operatora",
        "Status pomiaru WIDO",
        "Widzialność automat",
        "Status pomiaru WIDA",
        "Zachmurzenie ogólne",
        "Status pomiaru NOG",
        "Kierunek wiatru",
        "Status pomiaru KRWR",
        "Prędkość wiatru",
        "Status pomiaru FWR",
        "Poryw wiatru",
        "Status pomiaru PORW",
        "Temperatura powietrza",
        "Status pomiaru TEMP",
        "Temperatura termometru zwilżonego",
        "Status pomiaru TTZW",
        "Wskaźnik wentylacji",
        "Wskaźnik lodu",
        "Ciśnienie pary wodnej",
        "Status pomiaru CPW",
        "Wilgotność względna",
        "Status pomiaru WLGW",
        "Temperatura punktu rosy",
        "Status pomiaru TPTR",
        "Ciśnienie na poziomie stacji",
        "Status pomiaru PPPS",
        "Ciśnienie na poziomie morza",
        "Status pomiaru PPPM",
        "Charakterystyka tendencji",
        "Wartość tendencji",
        "Status pomiaru APP",
        "Opad za 6 godzin",
        "Status pomiaru WO6G",
        "Rodzaj opadu za 6 godzin",
        "Status pomiaru ROPT",
        "Pogoda bieżąca",
        "Pogoda ubiegła",
        "Zachmurzenie niskie",
        "Status pomiaru CLCM",
        "Chmury CL",
        "Status pomiaru CHCL",
        "Chmury CL tekstem",
        "Chmury CM",
        "Status pomiaru CHCM",
        "Chmury CM tekstem",
        "Chmury CH",
        "Status pomiaru CHCH",
        "Chmury CH tekstem",
        "Stan gruntu",
        "Status pomiaru SGRN",
        "Niedosyt wilgotności",
    ],
}
